### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#1]

**Comment by Ibedionu** [comment]
https://www.figma.com/file/oxADgo2x8JO3112423tTYU/Untitled?node-id=0%3A1&t=mBZbrZk1yR9ySFw4-1

**Comment by Ibedionu** [comment]
https://www.figma.com/file/oxADgo2x8JO3112423tTYU/Untitled?node-id=9%3A977&t=epWQwju0Pg9bCgjH-1

**Comment by Cozyamy** [comment]
nice
