### ISSUE TITLE
design sketch

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#2]

**Comment by sammuzor** [comment]
https://www.figma.com/file/oQxKoMtiOl2uehkm6DUON9/T%26C-Generator-Sketch?node-id=0%3A1&t=YNubN0aRVlqrmOmI-1

**Comment by sammuzor** [comment]
https://www.figma.com/file/I9uhmSVA7nl3CK2kR0OQiJ/Team-Newt2w-Mood-board?node-id=0%3A1&t=RSVglqyWQDxlRihH-1

**Comment by Pwidyluchi** [comment]
https://www.figma.com/file/4ynSqUQ1DgT0MWkbDQ3icX/PROJECT-PHASE-MILESTONE(T%26C)?t=fSvN9lRjea24BUWl-1

**Comment by sammuzor** [comment]
Contributed to the design sketch

**Comment by Dimpledee29** [comment]
I made a hand-drawn sketch according to the required designs and uploaded it on GitHub.

https://www.figma.com/file/oQxKoMtiOl2uehkm6DUON9/T%26C-Generator-Sketch?node-id=0%3A1&t=0K59FebhFobZsODu-1

**Comment by Cozyamy** [comment]
Good work team

**Comment by sammuzor** [comment]
Samuel opara
