### ISSUE TITLE
Log in and sign up page

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#26]

**Comment by Cozyamy** [comment]
Page is ready

**Comment by Comfortvize** [comment]
I built the code for the login and sign up page using html and css, attached to this is a screenshot of some of my code. 
![A03825B9-AB03-4DCC-9556-418DA72B3D78](https://user-images.githubusercontent.com/114366182/208801645-ef5fff58-5e8d-41f0-8472-470f4e44dcc8.jpeg)
 
![0C97D208-4C81-4663-9FFF-9469031CD60B](https://user-images.githubusercontent.com/114366182/208801636-baf390ed-825d-4518-ba2f-09db9c268486.jpeg)

![43BBFA9F-772A-4ED3-9D04-33DD0BB11612](https://user-images.githubusercontent.com/114366182/208801617-d5f79017-a153-4acd-950a-19deb19f4a21.jpeg)
