### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#3]

**Comment by Buildmychoice** [comment]
Done. ✅
https://www.figma.com/file/I9uhmSVA7nl3CK2kR0OQiJ/Team-Newt2w-Mood-board?node-id=0%3A1&t=RSVglqyWQDxlRihH-1

**Comment by Walkerofficial** [comment]
https://www.figma.com/file/I9uhmSVA7nl3CK2kR0OQiJ/Team-Newt2w-Mood-board?node-id=0%3A1&t=RSVglqyWQDxlRihH-1

Done

**Comment by Cozyamy** [comment]
Good job guys, thank you

**Comment by Cozyamy** [comment]
https://www.figma.com/file/I9uhmSVA7nl3CK2kR0OQiJ/Team-Newt2w-1st-Milestone?node-id=0%3A1&t=w75FK98UREzKbhH6-1
