### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#5]
https://www.figma.com/file/pRGRifQPxrwsxGk7USvGrS/Team-Newt2w---Database-Schema?node-id=1%3A2&t=DPS9hFG3O31VKChN-1

**Comment by joshiyke** [comment]
https://www.figma.com/file/pRGRifQPxrwsxGk7USvGrS/Team-Newt2w---Database-Schema?node-id=1%3A2&t=DPS9hFG3O31VKChN-1

**Comment by Ismailmoshood** [comment]
https://www.figma.com/file/pRGRifQPxrwsxGk7USvGrS/Team-Newt2w---Database-Schema?node-id=1%3A2&t=DPS9hFG3O31VKChN-1

Done✔

**Comment by Cozyamy** [comment]
Great
