### ISSUE TITLE
User flow and story

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/T_C_Gen-TeamNewt2w#6]

**Comment by Ibedionu** [comment]
https://www.figma.com/file/oxADgo2x8JO3112423tTYU/Untitled?node-id=0%3A1&t=mBZbrZk1yR9ySFw4-1

**Comment by Ibedionu** [comment]
https://www.figma.com/file/jTN69c3T0QhcrvCXQKHWl3/Flow-Charts-THE-VHUE-(Community)?node-id=0%3A1&t=qrUFNUqkx3pHp7ok-1

**Comment by Cozyamy** [comment]
good Job
